// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5124.WestTorranceLearn;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainLeftMotor1;
    public static SpeedController drivetrainLetMotor2;
    public static SpeedController drivetrainRightMotor1;
    public static SpeedController drivetrainRightMotor2;
    public static RobotDrive drivetrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftMotor1 = new VictorSP(0);
        LiveWindow.addActuator("Drivetrain", "LeftMotor1", (VictorSP) drivetrainLeftMotor1);
        
        drivetrainLetMotor2 = new VictorSP(1);
        LiveWindow.addActuator("Drivetrain", "LetMotor2", (VictorSP) drivetrainLetMotor2);
        
        drivetrainRightMotor1 = new VictorSP(2);
        LiveWindow.addActuator("Drivetrain", "RightMotor1", (VictorSP) drivetrainRightMotor1);
        
        drivetrainRightMotor2 = new VictorSP(3);
        LiveWindow.addActuator("Drivetrain", "RightMotor2", (VictorSP) drivetrainRightMotor2);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainLeftMotor1, drivetrainLetMotor2,
              drivetrainRightMotor1, drivetrainRightMotor2);
        
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);
        drivetrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        drivetrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        drivetrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        drivetrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
